# Generated by Django 3.1.1 on 2023-04-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20230423_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
