# Generated by Django 3.1.1 on 2023-05-01 05:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_suppliments'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 1, 5, 26, 7, 822084, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
