# Generated by Django 3.1.1 on 2023-05-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='check',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
