# Generated by Django 3.1.1 on 2023-05-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_enrollment_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=20)),
                ('card_date', models.CharField(max_length=20)),
                ('card_cvv', models.CharField(max_length=20)),
                ('card_name', models.CharField(max_length=30)),
            ],
        ),
    ]
