# Generated by Django 3.1.1 on 2023-05-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_user',
            name='status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
