# Generated by Django 4.1.6 on 2023-05-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_rename_check_enrollment_check1_alter_attendance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliments',
            name='details',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='suppliments',
            name='item',
            field=models.CharField(max_length=200),
        ),
    ]
