# Generated by Django 4.1.6 on 2023-05-04 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_suppliments_details_alter_suppliments_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=100)),
                ('video_category', models.CharField(max_length=100)),
                ('video', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='payment_videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=100)),
                ('video_category', models.CharField(max_length=100)),
                ('video', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authapp.contact')),
            ],
        ),
    ]
