# Generated by Django 4.1.6 on 2023-05-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_videos_payment_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_videos',
            name='payment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='payment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
