# Generated by Django 4.1.6 on 2023-05-04 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0018_video_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_videos',
            name='video_category',
        ),
    ]
