# Generated by Django 4.1.6 on 2023-05-04 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0019_remove_payment_videos_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_videos',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authapp.video_category'),
        ),
    ]
