# Generated by Django 4.1.6 on 2023-05-04 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0020_payment_videos_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='video_category',
        ),
        migrations.AddField(
            model_name='videos',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authapp.video_category'),
        ),
        migrations.AddField(
            model_name='videos',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authapp.contact'),
        ),
    ]
