# Generated by Django 4.1.6 on 2023-05-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0021_remove_videos_video_category_videos_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_videos',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
