# Generated by Django 4.1.6 on 2023-05-04 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0022_alter_payment_videos_video_alter_videos_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='user',
        ),
    ]
