# Generated by Django 4.1.6 on 2023-05-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0023_remove_videos_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_videos',
            name='user',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
