# Generated by Django 4.1.6 on 2023-05-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0024_alter_payment_videos_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_videos',
            name='category',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
