# Generated by Django 4.1.6 on 2023-05-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0025_alter_payment_videos_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='viewv_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('video_title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos/')),
                ('payment', models.IntegerField()),
            ],
        ),
    ]
