# Generated by Django 4.1.6 on 2023-05-04 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0026_viewv_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='viewv_video',
            new_name='view_video',
        ),
    ]
