# Generated by Django 4.1.6 on 2023-05-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0030_rename_customer_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='item',
        ),
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
