# Generated by Django 4.2.1 on 2023-05-23 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0031_remove_cartproduct_cart_remove_cartproduct_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
    ]
