# Generated by Django 4.2.1 on 2023-05-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0032_remove_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='Login',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='Logout',
        ),
    ]
