# Generated by Django 4.2.1 on 2023-05-23 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0033_remove_attendance_login_remove_attendance_logout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='DueDate',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='Reference',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='SelectMembershipplan',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='SelectTrainer',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='check1',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='paymentStatus',
        ),
    ]
