# Generated by Django 4.1.6 on 2023-05-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0035_user_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='trainer_img',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
    ]
